name: Como usar variaveis de ambiente
on:
  workflow_dispatch:
env:
  ENV_WORKFLOW: "VALOR WORKFLOW"
  
jobs:
  primeira-execucao:
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "PRIMEIRO JOB"
    steps:
      - name: Execucao
        env:
          ENV_ACTION: "PRIMEIRA EXECUCAO"      
        run: |
          echo "1 - $ENV_WORKFLOW"
          echo "3 - $ENV_JOB"
          echo "4 - $ENV_ACTION"

      - name: Execucao
        env:
          ENV_ACTION: "SEGUNDA SEGUNDA EXECUCAO"
        run: |
          echo "1 - $ENV_WORKFLOW"
          echo "3 - $ENV_JOB"
          echo "4 - $ENV_ACTION"

  segunda-execucao:
    needs: primeira-execucao
    runs-on: ubuntu-latest
    env:
      ENV_JOB: "SEGUNDO JOB"
    steps:
      - name: Execucao
        run: |
          echo "1 - $ENV_WORKFLOW"
          echo "2 - $ENV_JOB"
